export const USER_lOGIN_REQUEST="USER_LOGIN_REQUEST";
export const USER_lOGIN_SUCCESS="USER_LOGIN_SUCCESS";
export const USER_lOGOUT_SUCCESS="USER_LOGOUT_SUCCESS";
export const USER_lOGIN_ERROR ="USER_LOGIN_ERROR";